# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff8383f7adfb90290caa96dd1bfc9994"
name = "ReOrder Reminder Pro"
handle = "reorder-reminder1"
application_url = "https://reorder-shopify-app.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "deca-development-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_products,write_checkouts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://reorder-shopify-app.onrender.com/auth/callback",
  "https://reorder-shopify-app.onrender.com/auth/shopify/callback",
  "https://reorder-shopify-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["orders/fulfilled" ]
  uri = "/webhooks/order"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/product_delete"

[pos]
embedded = false
